### ISSUE TITLE
Allow quotes in FuncIRI

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/svgtypes#4]
This is a correct FuncIRI: `fill="url('#gfuser')"`

**Comment by JoKalliauer** [comment]
The author of the immage wrote at https://commons.wikimedia.org/w/index.php?title=User_talk:Glrx&oldid=399206211#fill=%22url('#gfuser')%22_allowed

    See https://svgwg.org/svg2-draft/painting.html#FillProperty that says the fill presentation property in SVG 2 may be of type <paint>.
    See https://svgwg.org/svg2-draft/painting.html#SpecifyingPaint that says <paint> may be a CSS <url> value.
    See https://www.w3.org/TR/css3-values/#url-value that says a <url> is url(<string>...).
    See https://www.w3.org/TR/css3-values/#string-value that says a string may use single or double quotation marks
    See https://www.w3.org/TR/css3-values/#urls that says a string inside url(...) may be written without quotation marks.

So it is definitly a SVG2.0, but not shure about SVG 1.1.

**Comment by RazrFalcon** [comment]
Thanks for clarification. I think I will add it anyway, since it doesn't affect much.

**Comment by romanzes** [comment]
Just stumbled upon an SVG file that was rendered as black-and-white by `resvg` and found out it was because of quotes around the IDs. I opened a pull request to add the support for quotes, would appreciate if you could take a look @RazrFalcon. Thanks!

## SVG
![quotes_in_iri](https://github.com/RazrFalcon/svgtypes/assets/5735967/f708482e-bb11-46c9-a199-ac437da36d68)
I opened a PR to fix that

## resvg output
![Copy of Untitled (6)](https://github.com/RazrFalcon/svgtypes/assets/5735967/32ec026e-3377-4f5f-a35f-98797e6e0f0b)
